# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  automated-tests:
    runs-on: ${{ matrix.os }}
    env: 
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
#         go_version: ['1.18', '1.17', '>=1.18']
#         os: ['ubuntu-latest','ubuntu-18.04']
        go_version: ['1.18']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
        os: ${{ matrix.os }}

    - name: Build-DB
      run: docker-compose build
      
    - name: Run-DB
      run: docker-compose up -d
    
    - name: Test
      run: go test -v main_test.go
      
    - name: Secret
      run: echo ${{ secrets.TESTE }}
  
  
  build:
    needs: automated-tests
    strategy:
      matrix:
        # os: ['ubuntu-latest','ubuntu-18.04']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: program
        path: main

  docker: 
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
